version: "3.8"

services:
  monolith:
    build:
      context: ../monolith
      dockerfile: Dockerfile
    container_name: hotelio-monolith
    ports:
      - "8084:8080"
    networks:
      - hotelio-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://monolith-db:5432/hotelio
      SPRING_DATASOURCE_USERNAME: hotelio
      SPRING_DATASOURCE_PASSWORD: hotelio
      BOOKING_SERVICE_EXTERNAL_HOST: booking-service
      BOOKING_SERVICE_EXTERNAL_PORT: 50051

  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "50051:50051"
    networks:
      - hotelio-net
    
  
  booking-history-service:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: booking-history-service
    networks:
      - hotelio-net


  monolith-db:
    image: postgres:15
    container_name: hotelio-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5432:5432"
    volumes:
      - monolith-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net


  booking-db:
    image: postgres:15
    container_name: booking-db
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking
    ports:
      - "5433:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  booking-history-db:
    image: postgres:15
    container_name: booking-history-db
    environment:
      POSTGRES_USER: booking-history
      POSTGRES_PASSWORD: booking-history
      POSTGRES_DB: booking-history
    ports:
      - "5434:5432"
    volumes:
      - booking-history-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net





  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hotelio-net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hotelio-net

volumes:
  monolith-db-data:
  booking-db-data:
  booking-history-db-data:


networks:
  hotelio-net:
    external: true
