version: '3.8'

services:
  apollo-gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - booking-subgraph
      - hotel-subgraph
      - promo-subgraph
     
    networks:
      - hotelio-net  

  booking-subgraph:
    build: ./booking-subgraph
    ports:
      - "4001:4001"
    networks:
      - hotelio-net    

  hotel-subgraph:
    build: ./hotel-subgraph
    ports:
      - "4002:4002"
    networks:
      - hotelio-net    


  promo-subgraph:
    build: ./promo-subgraph
    depends_on:
      - booking-subgraph
    ports:
      - "4003:4003"
    networks:
      - hotelio-net        

networks:
  hotelio-net:
    external: true      
